strategies:
  momentum_options:
    enabled: true
    description: "Momentum-based options strategy"
    parameters:
      rsi_period: 14
      rsi_overbought: 70
      rsi_oversold: 30
      volume_threshold: 1.5  # 1.5x average volume
      min_option_volume: 100
      min_open_interest: 500
    
  volatility_play:
    enabled: true
    description: "Trade options based on implied volatility"
    parameters:
      iv_percentile_threshold: 80  # High IV for selling
      iv_rank_threshold: 70
      delta_range: [0.25, 0.40]  # Delta neutral strategies
      days_to_expiration_min: 30
      days_to_expiration_max: 60
    
  trend_following:
    enabled: true
    description: "Follow market trends with options"
    parameters:
      ema_fast: 20
      ema_slow: 50
      macd_signal: 9
      atr_multiplier: 2.0
      trend_strength_min: 0.6

risk_management:
  max_portfolio_risk: 0.02  # 2% max risk per trade
  max_daily_trades: 10
  max_consecutive_losses: 3
  position_sizing_method: "kelly_criterion"
  
  stop_loss:
    type: "percentage"
    value: 0.15  # 15% stop loss
    
  take_profit:
    type: "percentage"
    value: 0.30  # 30% take profit
    
  time_stop:
    enabled: true
    days: 5  # Exit if no movement in 5 days

signals:
  confidence_threshold: 0.7  # Minimum confidence for trade
  signal_combination: "majority"  # majority, unanimous, weighted
  
  weights:
    technical: 0.4
    sentiment: 0.2
    options_flow: 0.2
    claude_analysis: 0.2

market_conditions:
  bull_market:
    vix_max: 20
    spy_above_ma200: true
    call_put_ratio_min: 1.2
    
  bear_market:
    vix_min: 25
    spy_below_ma200: true
    call_put_ratio_max: 0.8
    
  neutral_market:
    vix_range: [15, 25]
    spy_near_ma200: 0.02  # Within 2% of MA200