name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if secrets are set
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          echo "Testing secret availability..."
          
          # Check ANTHROPIC_API_KEY
          if [ -z "$ANTHROPIC_API_KEY" ]; then
            echo "❌ ANTHROPIC_API_KEY is NOT set or is empty"
          else
            echo "✅ ANTHROPIC_API_KEY is set"
            echo "   Length: ${#ANTHROPIC_API_KEY} characters"
            echo "   First 7 chars: ${ANTHROPIC_API_KEY:0:7}..."
            echo "   Last 4 chars: ...${ANTHROPIC_API_KEY: -4}"
          fi
          
          # Test with Python
          python3 -c "
import os
key = os.getenv('ANTHROPIC_API_KEY')
if key:
    print(f'✅ Python can access ANTHROPIC_API_KEY')
    print(f'   Starts with: {key[:10]}...')
    print(f'   Key format looks like Anthropic: {key.startswith(\"sk-ant-\")}'
else:
    print('❌ Python cannot access ANTHROPIC_API_KEY')
          "